---
controller:
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 5
rbac:
  create: true
  ## Name of the ingress class to route through this controller
  ##
ingressClass: redirects-nginx
